# Generated by Django 2.2 on 2020-06-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyToDoList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('contents', models.TextField()),
                ('entryData', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
