# Generated by Django 2.2 on 2020-06-20 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytodolist',
            old_name='entryData',
            new_name='entryDate',
        ),
    ]
